#!/bin/sh
# -------------------------------------------------------------------------
#  Nginx-ws - Daily Update Cronjob
# -------------------------------------------------------------------------
# Website:       https://www.wooserv.net
# GitHub:        https://github.com/ihfbib/nginx-ws
# Copyright (c) 2022 WooServ <contact@wooserv.com>
# This script is licensed under M.I.T
# -------------------------------------------------------------------------
# Version 1.0.0 - 2022-03-17
# -------------------------------------------------------------------------

##################################
# Check Nginx version and modules
##################################

if [ -x /usr/sbin/nginx ]; then

    CURRENT_NGINX="$(/usr/sbin/nginx -v 2>&1 | awk -F "/" '{print $2}' | awk -F " " '{print $1}')"
    NGINX_MAINLINE="$(/usr/bin/curl -sL https://nginx.org/en/download.html 2>&1 | grep -E -o 'nginx\-[0-9.]+\.tar[.a-z]*' | awk -F "nginx-" '/.tar.gz$/ {print $2}' | sed -e 's|.tar.gz||g' | head -n 1 2>&1)"
    NGINX_STABLE="$(/usr/bin/curl -sL https://nginx.org/en/download.html 2>&1 | grep -E -o 'nginx\-[0-9.]+\.tar[.a-z]*' | awk -F "nginx-" '/.tar.gz$/ {print $2}' | sed -e 's|.tar.gz||g' | head -n 2 | grep 1.20 2>&1)"
    NAXSI="$(/usr/sbin/nginx -V 2>&1 | grep naxsi)"
    RTMP="$(/usr/sbin/nginx -V 2>&1 | grep rtmp)"

else
    echo "Nginx is not installed"
    exit 1
fi

##################################
# Check if new release is available
##################################

if [ "$CURRENT_NGINX" != "$NGINX_MAINLINE" ] && [ "$CURRENT_NGINX" != "$NGINX_STABLE" ]; then
    [ ! -d $HOME/.scripts ] && {
        mkdir -p $HOME/.scripts
    }
    wget -O $HOME/.scripts/nginx-build.sh https://raw.githubusercontent.com/ihfbib/nginx-ws/master/nginx-build.sh > /dev/null 2>&1
    chmod +x $HOME/.scripts/nginx-build.sh

    if [ -n "$NAXSI" ]; then
        NAXSI_ARG="--naxsi"
    else
        NAXSI_ARG=""
    fi

    if [ -n "$RTMP" ]; then
        RTMP_ARG="--rtmp"
    else
        RTMP_ARG=""
    fi

    if [ -n "$CURRENT_STABLE" ]; then
        $HOME/.scripts/nginx-build.sh --stable "$NAXSI_ARG" "$RTMP_ARG" > /dev/null 2>&1
    else
        $HOME/.scripts/nginx-build.sh "$NAXSI_ARG" "$RTMP_ARG" > /dev/null 2>&1
    fi
fi